// components/ui/EmptyState.vue
<template>
  <div class="relative flex flex-col items-center justify-center overflow-hidden rounded-[--ka-r-lg] px-6 py-12 text-center">
    <component :is="icon" v-if="icon" class="mb-4 h-16 w-16 text-[--ka-fg-muted] opacity-30" />
    <h3 v-if="title" class="text-lg font-semibold text-[--ka-fg]">{{ title }}</h3>
    <p v-if="description" class="mt-1 max-w-md text-sm text-[--ka-fg-2]">{{ description }}</p>
    <NuxtLink v-if="actionLabel && actionLink" :to="actionLink" class="btn-primary mt-5">
      {{ actionLabel }}
    </NuxtLink>
    <Button v-else-if="actionLabel" class="mt-5" type="button" @click="$emit('action')">
      {{ actionLabel }}
    </Button>
  </div>
</template>

<script setup lang="ts">
import type { Component } from "vue";

defineProps<{
  icon?: Component;
  title?: string;
  description?: string;
  actionLabel?: string;
  actionLink?: string;
}>();

defineEmits<{
  action: [];
}>();
</script>

// components/ui/EmptyState.tsx
'use client'

import Link from 'next/link'
import { cn } from './utils'

export function EmptyState({
  title,
  description,
  action,
  className,
}: {
  title: string
  description?: string
  action?: { label: string; href: string } | { label: string; onClick: () => void }
  className?: string
}) {
  return (
    <div className={cn('ui-card rounded-[var(--radius-xl)] p-6 text-center', className)}>
      <p className="text-sm font-semibold" style={{ color: 'var(--text)' }}>
        {title}
      </p>
      {description && (
        <p className="text-sm mt-1.5" style={{ color: 'var(--muted)' }}>
          {description}
        </p>
      )}
      {action && (
        <div className="mt-4">
          {'href' in action ? (
            <Link
              href={action.href}
              className="inline-flex items-center justify-center ui-btn ui-btn-primary h-10 px-4 text-sm font-medium rounded-[var(--radius-md)]"
            >
              {action.label}
            </Link>
          ) : (
            <button
              type="button"
              onClick={action.onClick}
              className="inline-flex items-center justify-center ui-btn ui-btn-primary h-10 px-4 text-sm font-medium rounded-[var(--radius-md)]"
            >
              {action.label}
            </button>
          )}
        </div>
      )}
    </div>
  )
}
